### ISSUE TITLE
formatCurrency why they are not work with instantly with when TextInput  onChangeText call 

### ISSUE THREAD

**Issue by parth-shiroya** [AwesomeLabs/react-native-format-currency#5]
![Screenshot at Nov 18 16-29-02](https://user-images.githubusercontent.com/102135385/202690357-64283855-f835-4569-b2cd-28d3fcc9ca50.png)
![Screenshot at Nov 18 16-29-14](https://user-images.githubusercontent.com/102135385/202690370-3fa60e75-7314-4d4d-bbb8-7bc306a9fdde.png)

**Comment by btroia** [comment]
Hi, closing because this appears to be a non-library related issue
